[0m23:28:22.709177 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f4ff75e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f4e12a740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f4e12a5c0>]}


============================== 23:28:22.711296 | d952cc68-70a8-4a64-a6e6-0516c2e7d183 ==============================
[0m23:28:22.711296 [info ] [MainThread]: Running with dbt=1.6.1
[0m23:28:22.711803 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/zh2408/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:28:28.775628 [debug] [MainThread]: Starter project path: /opt/conda/lib/python3.10/site-packages/dbt/include/starter_project
[0m23:28:28.819095 [info ] [MainThread]: 
Your new dbt project "tpcdi" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:28:28.819472 [info ] [MainThread]: Setting up your profile.
[0m23:28:33.139204 [info ] [MainThread]: No sample profile found for duckdb.
[0m23:28:33.139992 [debug] [MainThread]: Command `dbt init` succeeded at 23:28:33.139881 after 10.51 seconds
[0m23:28:33.140364 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f4ff75e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f4951b040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1f4e12a590>]}
[0m23:28:33.140767 [debug] [MainThread]: Flushing usage events
[0m22:01:21.492444 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc24b865e70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc249a22950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc249a22920>]}


============================== 22:01:21.527721 | a4395fa8-734c-4960-b57e-b729350bad92 ==============================
[0m22:01:21.527721 [info ] [MainThread]: Running with dbt=1.6.1
[0m22:01:21.528436 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/zh2408/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:01:21.528940 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/zh2408/public_tpc_di/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:01:21.529564 [debug] [MainThread]: Command `dbt docs generate` failed at 22:01:21.529469 after 0.11 seconds
[0m22:01:21.529950 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc24b865e70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc249a228c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc249a22c50>]}
[0m22:01:21.530376 [debug] [MainThread]: Flushing usage events
